In [13]:
import pandas as pd
import glob

In [14]:
# load all csv files in the folder
df_list = {}
for filename in glob.glob('*.csv'):
    df_list[filename] = pd.read_csv(filename)

In [15]:
for k, v in df_list.items():
    print(k)
    display(v)

finished_paths_appended_metrics.csv

,Unnamed: 0,hashedIpAddress,timestamp,durationInSec,path,rating,slope_path_degree_before,slope_path_degree_after,slope_path_clustering_before,slope_path_clustering_after,slope_path_degree_centrality_before,slope_path_degree_centrality_after,slope_path_betweenness_before,slope_path_betweenness_after,slope_path_closeness_before,slope_path_closeness_after
0,0,6a3701d319fc3754,2011-02-15 03:26:49,166,"['14th_century', '15th_century', '16th_century...",NaN,8.571429,-58.3,-0.016738,0.018619,0.001867,-0.012699,0.000526,-0.002381,0.000736,-0.028686
1,1,3824310e536af032,2012-08-12 06:36:52,88,"['14th_century', 'Europe', 'Africa', 'Atlantic...",3.0,39.800000,-118.3,-0.034423,0.006470,0.008669,-0.025768,0.000654,-0.003020,0.012319,-0.046951
2,2,415612e93584d30e,2012-10-03 21:10:40,138,"['14th_century', 'Niger', 'Nigeria', 'British_...",NaN,192.500000,-270.2,-0.076322,0.017899,0.041930,-0.058854,0.001335,0.001212,0.055409,-0.048090
3,3,64dd5cd342e3780c,2010-02-08 07:25:25,37,"['14th_century', 'Renaissance', 'Ancient_Greec...",NaN,13.000000,-46.5,-0.001743,0.006580,0.002832,-0.010129,0.002804,-0.010425,-0.001075,-0.023496
4,4,015245d773376aab,2013-04-23 15:27:08,175,"['14th_century', 'Italy', 'Roman_Catholic_Chur...",3.0,-15.000000,-25.5,-0.028404,-0.002866,-0.003267,-0.005554,0.000592,-0.000493,-0.002279,-0.003045
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51313,51313,15a13a1d66ef5456,2012-10-03 02:23:35,66,"['Yagan', 'Ancient_Egypt', 'Civilization']",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51314,51314,2ef7ac844cefda58,2011-03-16 05:42:18,165,"['Yagan', 'Folklore', 'Brothers_Grimm', '<', '...",3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51315,51315,12863abb7887f890,2013-11-22 04:42:52,228,"['Yagan', 'Australia', 'England', 'France', 'U...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51316,51316,19f8284371753362,2011-02-27 07:42:47,56,"['Yarralumla%2C_Australian_Capital_Territory',...",1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51317,51317,24b84602179de377,2011-10-09 01:11:41,30,"['Ziad_Jarrah', 'Germany', 'Jew']",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

finished_paths_pairs_metrics.csv

,index,from,to,timestamp,hashedIpAddress,durationInSec,degree_from,clustering_from,closeness_from,betweenness_from,degree_centrality_from,degree_to,clustering_to,closeness_to,betweenness_to,degree_centrality_to
0,0,14th_century,15th_century,2011-02-15 03:26:49,6a3701d319fc3754,166,102.0,0.109545,0.376616,0.000509,0.022217,157.0,0.117474,0.410642,0.001758,0.034197
1,1,15th_century,16th_century,2011-02-15 03:26:49,6a3701d319fc3754,166,157.0,0.117474,0.410642,0.001758,0.034197,216.0,0.082022,0.418145,0.003494,0.047049
2,2,16th_century,Pacific_Ocean,2011-02-15 03:26:49,6a3701d319fc3754,166,216.0,0.082022,0.418145,0.003494,0.047049,272.0,0.065309,0.445451,0.004196,0.059246
3,3,Pacific_Ocean,Atlantic_Ocean,2011-02-15 03:26:49,6a3701d319fc3754,166,272.0,0.065309,0.445451,0.004196,0.059246,375.0,0.051939,0.468668,0.008487,0.081682
4,4,Atlantic_Ocean,Accra,2011-02-15 03:26:49,6a3701d319fc3754,166,375.0,0.051939,0.468668,0.008487,0.081682,20.0,0.234043,0.341492,0.000015,0.004356
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295455,295455,Yarralumla%2C_Australian_Capital_Territory,Australia,2011-02-27 07:42:47,19f8284371753362,56,41.0,0.248474,0.262714,0.000002,0.008931,649.0,0.026187,0.500220,0.012527,0.141364
295456,295456,Australia,United_States,2011-02-27 07:42:47,19f8284371753362,56,649.0,0.026187,0.500220,0.012527,0.141364,1845.0,0.018451,0.590353,0.094090,0.401873
295457,295457,United_States,Abraham_Lincoln,2011-02-27 07:42:47,19f8284371753362,56,1845.0,0.018451,0.590353,0.094090,0.401873,97.0,0.122898,0.390997,0.000780,0.021128
295458,295458,Ziad_Jarrah,Germany,2011-10-09 01:11:41,24b84602179de377,30,26.0,0.220679,0.284198,0.000003,0.005663,912.0,0.041854,0.524285,0.019409,0.198650
295459,295459,Germany,Jew,2011-10-09 01:11:41,24b84602179de377,30,912.0,0.041854,0.524285,0.019409,0.198650,354.0,0.065782,0.454881,0.003151,0.077107

nodes_w_graph_metrics.csv

,Unnamed: 0,node_name,degree,clustering,closeness,betweenness,degree_centrality
0,0,Mona_Lisa,51,0.135827,0.342232,5.373976e-04,0.011109
1,1,William_Butler_Yeats,36,0.111643,0.333553,1.040548e-04,0.007841
2,2,Demosthenes,38,0.142857,0.309781,1.017386e-04,0.008277
3,3,Olympic_Games,196,0.102416,0.430211,3.252474e-03,0.042692
4,4,Mausoleum_of_Maussollos,26,0.087692,0.000000,0.000000e+00,0.005663
...,...,...,...,...,...,...,...
4587,4587,2-6-0,6,0.357143,0.203622,6.724583e-06,0.001307
4588,4588,Battle_of_Bicocca,12,0.500000,0.209772,1.536202e-07,0.002614
4589,4589,Margin_of_error,5,0.100000,0.289409,8.737545e-06,0.001089
4590,4590,Dennis_Ritchie,10,0.204545,0.234118,3.674165e-05,0.002178
4591,4591,El_Ni%C3%B1o-Southern_Oscillation,53,0.135793,0.349257,1.123587e-04,0.011544

unfinished_paths_appended_metrics.csv

,Unnamed: 0,hashedIpAddress,timestamp,durationInSec,path,target,type,slope_path_degree_before,slope_path_degree_after,slope_path_clustering_before,slope_path_clustering_after,slope_path_degree_centrality_before,slope_path_degree_centrality_after,slope_path_betweenness_before,slope_path_betweenness_after,slope_path_closeness_before,slope_path_closeness_after
0,0,2426091a53125110,2011-02-07 05:02:15,1804,['Obi-Wan_Kenobi'],Microsoft,timeout,-144.000000,-58.000000,-0.002536,0.030618,-0.031366,-0.012633,-0.004739,-0.000037,-0.136704,0.016012
1,1,26141fd878806294,2011-02-07 05:14:11,1805,['Julius_Caesar'],Caracas,timeout,352.000000,-59.885714,0.013983,-0.025478,0.076672,-0.013044,0.003044,-0.001250,0.134805,-0.011348
2,2,2b015fb8181c48f2,2011-02-07 15:00:19,1818,"['Malawi', 'Democracy', 'Alexander_the_Great']",First_Crusade,timeout,9.314286,-23.900000,0.000119,0.017025,0.002029,-0.005206,0.000160,-0.000103,-0.001984,0.002978
3,3,53a53bc244e08a6a,2011-02-07 16:06:01,49,['Paraguay'],Mount_St._Helens,restart,298.800000,-240.700000,-0.114070,-0.003121,0.065084,-0.052429,0.008193,-0.011726,0.053908,-0.053562
4,4,53a53bc244e08a6a,2011-02-07 17:18:25,1808,"['Paraguay', 'Bolivia']",Mount_St._Helens,timeout,416.000000,-389.500000,-0.012677,0.000798,0.090612,-0.084840,0.007676,-0.007260,0.063721,-0.061504
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24870,24870,109ed71f571d86e9,2014-01-15 12:06:45,180,"['Franz_Kafka', 'Tuberculosis', 'World_Health_...",Cholera,restart,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24871,24871,232f992e57d43e8d,2014-01-15 12:08:17,6,['Modern_history'],Hollandic,restart,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24872,24872,2e09a7224600a7cd,2014-01-15 15:06:40,1900,"['Computer_programming', 'Linguistics', 'Cultu...",The_Beatles,timeout,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24873,24873,60af9e2138051b96,2014-01-15 15:24:41,1903,"['Jamaica', 'United_Kingdom', 'World_War_II', ...",Alan_Turing,timeout,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24874,24874,1cf0cbb3281049ab,2014-01-15 21:54:01,352,"['Mark_Antony', 'Rome', 'Tennis', 'Hawk-Eye', ...",Feather,restart,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

unfinished_paths_pairs_metrics.csv

,index,from,to,timestamp,hashedIpAddress,durationInSec,degree_from,clustering_from,closeness_from,betweenness_from,degree_centrality_from,degree_to,clustering_to,closeness_to,betweenness_to,degree_centrality_to
0,0,Malawi,Democracy,2011-02-07 15:00:19,2b015fb8181c48f2,1818,158.0,0.256161,0.368995,0.000350,0.034415,197.0,0.078215,0.436363,0.001303,0.042910
1,1,Democracy,Alexander_the_Great,2011-02-07 15:00:19,2b015fb8181c48f2,1818,197.0,0.078215,0.436363,0.001303,0.042910,134.0,0.090761,0.373878,0.000793,0.029188
2,2,Paraguay,Bolivia,2011-02-07 17:18:25,53a53bc244e08a6a,1808,59.0,0.227086,0.371722,0.000046,0.012851,129.0,0.121858,0.385368,0.000734,0.028098
3,3,Agriculture,History_of_the_world,2011-02-07 17:42:37,131600803df4895e,2009,298.0,0.044390,0.470257,0.004923,0.064910,154.0,0.110842,0.333553,0.000184,0.033544
4,4,History_of_the_world,China,2011-02-07 17:42:37,131600803df4895e,2009,154.0,0.110842,0.333553,0.000184,0.033544,586.0,0.033223,0.503189,0.010256,0.127641
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
104415,104415,World_War_II,Battle_of_Midway,2014-01-15 15:24:41,60af9e2138051b96,1903,870.0,0.032808,0.523446,0.015500,0.189501,27.0,0.289244,0.345018,0.000278,0.005881
104416,104416,Mark_Antony,Rome,2014-01-15 21:54:01,1cf0cbb3281049ab,352,35.0,0.233051,0.326836,0.000054,0.007624,286.0,0.058031,0.446320,0.002788,0.062296
104417,104417,Rome,Tennis,2014-01-15 21:54:01,1cf0cbb3281049ab,352,286.0,0.058031,0.446320,0.002788,0.062296,119.0,0.112818,0.432120,0.003297,0.025920
104418,104418,Tennis,Hawk-Eye,2014-01-15 21:54:01,1cf0cbb3281049ab,352,119.0,0.112818,0.432120,0.003297,0.025920,14.0,0.198864,0.302053,0.000253,0.003049
104419,104419,Hawk-Eye,Computer,2014-01-15 21:54:01,1cf0cbb3281049ab,352,14.0,0.198864,0.302053,0.000253,0.003049,123.0,0.038518,0.427438,0.006296,0.026792